const main = async () => {
  console.log('Time to get started!');
};

main().catch((err) => console.error(err));
